# Datos de StatsBomb

Ejecuta las celdas en orden. La cuenta tiene acceso a varias temporadas de Liga MX y Liga MX Femenil. Cada bloque importa un recurso de la API como DataFrame o diccionario de DataFrames.

## 0. Librerías y credenciales

Las credenciales están en `.env`, excluido de Git. Usa el kernel **Python (Hackaton-America)**. [Referencia del cliente oficial](https://github.com/hudl/statsbombpy/blob/master/README.md).

In [15]:
import json
import os
from pathlib import Path

import numpy as np
import pandas as pd
import requests
import sklearn
from dotenv import load_dotenv

load_dotenv(".env")
usuario = os.getenv("API_USERNAME")
contrasena = os.getenv("API_PASSWORD")
if not usuario or not contrasena:
    raise ValueError("Completa API_USERNAME y API_PASSWORD en .env")
credenciales = {"user": usuario, "passwd": contrasena}

from statsbombpy import sb

print(f"pandas {pd.__version__} | numpy {np.__version__} | scikit-learn {sklearn.__version__}")

pandas 2.3.3 | numpy 2.3.5 | scikit-learn 1.9.1

## 1. Competiciones y temporadas

`competiciones` contiene todas las combinaciones disponibles para esta cuenta. Los identificadores `competition_id` y `season_id` sirven para las siguientes consultas.

In [16]:
competiciones = sb.competitions(creds=credenciales)
display(competiciones[["competition_id", "season_id", "competition_name", "season_name"]])

   competition_id  season_id competition_name season_name
0              73        351          Liga MX   2026/2027
1              73        318          Liga MX   2025/2026
2              73        317          Liga MX   2024/2025
3              73        281          Liga MX   2023/2024
4              73        235          Liga MX   2022/2023
5              73        108          Liga MX   2021/2022
6            1438        351  Liga MX Femenil   2026/2027
7            1438        318  Liga MX Femenil   2025/2026
8            1438        317  Liga MX Femenil   2024/2025

## 2. Partidos de una temporada

El ejemplo usa Liga MX 2025/2026. Cambia los identificadores según la tabla anterior.

In [17]:
competition_id = 73
season_id = 318
partidos = sb.matches(competition_id=competition_id, season_id=season_id, creds=credenciales)
display(partidos[["match_id", "match_date", "home_team", "away_team"]].head())

   match_id  match_date    home_team   away_team
0   4004046  2025-07-13       Toluca      Necaxa
1   4059422  2026-05-22    Cruz Azul  Pumas UNAM
2   4038901  2026-03-21       Necaxa     Tijuana
3   4038891  2026-03-15  Tigres UANL   Querétaro
4   4038820  2026-01-17       Necaxa       Atlas

## 3. Elegir un partido

Los siguientes bloques consultan el mismo `match_id`. Puedes cambiarlo por cualquier identificador de `partidos`.

In [18]:
match_id = int(partidos.iloc[0]["match_id"])
print("Partido seleccionado:", match_id)

Partido seleccionado: 4004046

## 4. Alineaciones

El resultado es un diccionario: cada equipo tiene su propio DataFrame.

In [19]:
alineaciones = sb.lineups(match_id=match_id, creds=credenciales)
for equipo, tabla in alineaciones.items():
    print(equipo, len(tabla), "jugadores")
    display(tabla.head())

Necaxa 21 jugadores

,player_id,player_name,player_nickname,birth_date,player_gender,player_height,player_weight,jersey_number,positions,stats,country,skills,formations,events
0,26268,Alexis Francisco Peña López,Alexis Peña,1996-01-13,male,187.0,81.0,4,"[{'position_id': 3, 'position': 'Right Center ...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Mexico,"{'HOPS': {'rating': 0.5868, 'raw_rating': 443....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
1,26312,Cristian Yonathan Calderón Del Real,Cristian Calderón,1997-05-24,male,177.0,66.0,16,"[{'position_id': 8, 'position': 'Left Wing Bac...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Mexico,"{'HOPS': {'rating': 0.5467, 'raw_rating': 414....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
2,27762,Luis Ezequiel Unsain,Ezequiel Unsain,1995-03-09,male,188.0,83.0,22,"[{'position_id': 1, 'position': 'Goalkeeper', ...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Argentina,"{'HOPS': {'rating': 0.5166, 'raw_rating': 393....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
3,28480,Tomás Oscar Badaloni,Tomás Badaloni,2000-05-02,male,187.0,82.0,9,"[{'position_id': 5, 'position': 'Left Center B...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Argentina,"{'HOPS': {'rating': 0.5807, 'raw_rating': 438....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
4,28815,Agustín Palavecino,None,1996-11-09,male,179.0,73.0,8,"[{'position_id': 11, 'position': 'Left Defensi...","{'own_goals': 0, 'goals': 0, 'assists': 1, 'pe...",Argentina,"{'HOPS': {'rating': 0.3514, 'raw_rating': 275....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."

Toluca 21 jugadores

,player_id,player_name,player_nickname,birth_date,player_gender,player_height,player_weight,jersey_number,positions,stats,country,skills,formations,events
0,5575,Héctor Miguel Herrera López,Héctor Herrera,1990-04-19,male,183.0,70.0,16,[],[],Mexico,"{'HOPS': {'rating': 0.4781, 'raw_rating': 367....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
1,5576,Jesús Daniel Gallardo Vasconcelos,Jesús Gallardo,1994-08-15,male,178.0,70.0,20,"[{'position_id': 6, 'position': 'Left Back', '...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Mexico,"{'HOPS': {'rating': 0.5727, 'raw_rating': 433....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
2,18784,João Paulo Dias Fernandes,Paulinho,1992-11-09,male,188.0,75.0,26,"[{'position_id': 23, 'position': 'Center Forwa...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Portugal,"{'HOPS': {'rating': 0.59, 'raw_rating': 445.46...","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
3,25135,Luan Garcia Teixeira,Luan,1993-05-10,male,189.0,86.0,13,"[{'position_id': 3, 'position': 'Right Center ...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Brazil,"{'HOPS': {'rating': 0.6386, 'raw_rating': 481....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
4,25342,Helio Junio Nunes de Castro,Helinho,2000-04-25,male,175.0,66.0,11,"[{'position_id': 24, 'position': 'Left Center ...","{'own_goals': 0, 'goals': 1, 'assists': 0, 'pe...",Brazil,"{'HOPS': {'rating': 0.4127, 'raw_rating': 320....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."

## 5. Eventos

Pases, tiros y el resto de acciones del partido en un DataFrame.

In [20]:
eventos = sb.events(match_id=match_id, creds=credenciales)
print(len(eventos), "eventos")
display(eventos.head())

3538 eventos

/mnt/c/Users/Adrián/Desktop/Hackaton-America/.venv/lib/python3.14/site-packages/statsbombpy/sb.py:173: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  events = pd.concat([*events.values()], axis=0, ignore_index=True, sort=True)

,50_50,attacking_direction,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_duel_win_probability,clearance_head,clearance_left_foot,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,right_to_left,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Toluca,1227,00:00:00.000,Starting XI,NaN
1,NaN,left_to_right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 343, 'lineup': [{'player': {'id'...",Necaxa,1221,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Toluca,1227,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Necaxa,1221,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Toluca,1227,00:00:00.000,Half Start,NaN

## 6. Datos 360

Posiciones de jugadores visibles y áreas visibles asociadas a eventos, si están disponibles. Esta tabla puede ser grande.

In [21]:
frames_360 = sb.frames(match_id=match_id, creds=credenciales)
print(len(frames_360), "filas 360")
display(frames_360.head())

39429 filas 360

,id,visible_area,match_id,teammate,actor,keeper,location,distance_from_edge_of_visible_area
0,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[41.4, 34.3]",14.88
1,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[49.1, 49.6]",14.31
2,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[50.7, 40.4]",20.12
3,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[60.2, 54.5]",18.46
4,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[60.3, 63.6]",9.36

## 7. Estadísticas de jugadores por partido

In [22]:
estadisticas_jugadores_partido = sb.player_match_stats(match_id=match_id, creds=credenciales)
print(len(estadisticas_jugadores_partido), "jugadores")
display(estadisticas_jugadores_partido.head())

32 jugadores

,account_id,match_id,team_id,team_name,player_id,player_name,player_match_minutes,player_match_np_xg,player_match_np_shots,player_match_goals,...,player_match_fhalf_obv_passes_360,player_match_f3_obv_passes_360,player_match_challenge_ratio,player_match_obv_defensive_action,player_match_average_lbp_to_space_distance,player_match_fhalf_average_lbp_to_space_distance,player_match_f3_average_lbp_to_space_distance,player_match_aerial_ratio,player_match_box_cross_ratio,player_match_claim_success
0,41100,4004046,1221,Necaxa,27762,Luis Ezequiel Unsain,97.370100,0.000000,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41100,4004046,1227,Toluca,18784,João Paulo Dias Fernandes,67.012850,0.544052,3,0,...,-0.107849,-0.082712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41100,4004046,1221,Necaxa,26312,Cristian Yonathan Calderón Del Real,84.759583,0.000000,0,0,...,0.012735,0.008121,0.000000,0.056141,5.850117,4.166835,4.166835,NaN,NaN,NaN
3,41100,4004046,1221,Necaxa,31462,José Iván Rodríguez Rebollar,84.759583,0.000000,0,0,...,0.054474,0.018808,0.666667,-0.036769,2.381114,2.468333,NaN,0.5,NaN,NaN
4,41100,4004046,1227,Toluca,87434,Robert Osmar Morales Benítez,30.357250,0.000000,0,0,...,0.003942,-0.001854,1.000000,-0.047213,9.587577,9.587577,NaN,1.0,NaN,NaN

## 8. Estadísticas de equipos por partido

In [23]:
estadisticas_equipos_partido = sb.team_match_stats(match_id=match_id, creds=credenciales)
print(len(estadisticas_equipos_partido), "equipos")
display(estadisticas_equipos_partido.head())

2 equipos

,account_id,match_id,team_id,team_name,opposition_id,opposition_name,competition_id,competition_name,season_id,season_name,...,team_match_transition_possession_rate,team_match_time_in_transition,team_match_time_in_control,team_match_transition_xg,team_match_transition_xg_conceded,team_match_transition_obv,team_match_transition_obv_conceded,team_match_avg_team_possession_directness,team_match_avg_team_possession_directness_in_control,team_match_avg_team_possession_directness_in_transition
0,41100,4004046,1227,Toluca,1221,Necaxa,73,Liga MX,318,2025/2026,...,0.205000,431460.0,1146413.0,0.000000,0.597497,0.929267,1.850932,0.520801,0.485136,0.813583
1,41100,4004046,1221,Necaxa,1227,Toluca,73,Liga MX,318,2025/2026,...,0.194175,464283.0,877390.0,0.597497,0.000000,1.850932,0.929267,0.513537,0.484363,0.708028

## 9. Estadísticas de jugadores por temporada

In [24]:
estadisticas_jugadores_temporada = sb.player_season_stats(
    competition_id=competition_id, season_id=season_id, creds=credenciales
)
print(len(estadisticas_jugadores_temporada), "jugadores")
display(estadisticas_jugadores_temporada.head())

615 jugadores

,account_id,player_id,player_name,team_id,team_name,competition_id,competition_name,season_id,season_name,country_id,...,player_season_pressured_pass_length_ratio,player_season_obv_shot_90,player_season_average_lbp_to_space_distance,player_season_fhalf_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_received_distance,player_season_penalty_conversion_ratio,player_season_gsaa_ratio,player_season_ot_shots_faced_ratio,player_season_obv_gk_90
0,41100,126602,Anwar Kameel Ben Rhouma Torres,2773,Mazatlán,73,Liga MX,318,2025/2026,241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41100,35477,Cade Dylan Cowell,1297,Guadalajara,73,Liga MX,318,2025/2026,241,...,0.976813,0.080499,3.738889,3.876250,3.876250,4.105087,NaN,NaN,NaN,NaN
2,41100,115623,Daniel Aguirre,1297,Guadalajara,73,Liga MX,318,2025/2026,241,...,0.913612,0.010138,4.608344,4.425457,3.884393,4.114299,NaN,NaN,NaN,NaN
3,41100,16259,Marco Antonio Farfan,1300,Tigres UANL,73,Liga MX,318,2025/2026,241,...,0.938596,-0.025093,4.450345,4.444000,4.138000,6.739167,NaN,NaN,NaN,NaN
4,41100,45608,Walter Portales,1226,Puebla,73,Liga MX,318,2025/2026,241,...,0.876377,-0.013762,5.130000,4.216667,3.700000,6.160000,NaN,NaN,NaN,NaN

## 10. Estadísticas de equipos por temporada

In [25]:
estadisticas_equipos_temporada = sb.team_season_stats(
    competition_id=competition_id, season_id=season_id, creds=credenciales
)
print(len(estadisticas_equipos_temporada), "equipos")
display(estadisticas_equipos_temporada.head())

18 equipos

,account_id,team_name,team_id,competition_id,competition_name,season_id,season_name,team_female,team_season_matches,team_season_gd,...,team_season_transition_possession_rate,team_season_time_in_transition_pg,team_season_time_in_control_pg,team_season_transition_xg_pg,team_season_transition_xg_conceded_pg,team_season_transition_obv_pg,team_season_transition_obv_conceded_pg,team_season_avg_team_possession_directness,team_season_avg_team_possession_directness_in_control,team_season_avg_team_possession_directness_in_transition
0,41100,América,1229,73,Liga MX,318,2025/2026,False,38,17,...,0.186597,473378.053474,1.126048e+06,0.246345,0.205340,1.008726,0.731307,0.506469,0.492236,0.633129
1,41100,Atlas,1296,73,Liga MX,318,2025/2026,False,36,-15,...,0.196638,397045.845500,7.148278e+05,0.172453,0.335777,0.648232,0.847870,0.498507,0.472655,0.636179
2,41100,Cruz Azul,1224,73,Liga MX,318,2025/2026,False,44,30,...,0.202646,522148.442523,9.368695e+05,0.319651,0.264333,0.943876,0.971734,0.535875,0.518728,0.649179
3,41100,Guadalajara,1297,73,Liga MX,318,2025/2026,False,40,21,...,0.188370,497701.944075,9.941520e+05,0.415433,0.303820,0.985432,0.979473,0.511265,0.497692,0.609159
4,41100,León,1302,73,Liga MX,318,2025/2026,False,34,-27,...,0.192366,476671.899971,9.696429e+05,0.268190,0.320342,0.981189,1.184412,0.509142,0.487921,0.657076

## 14. DataFrames para análisis

Este bloque reúne las tablas para análisis. `df_partidos` carga todos los archivos `partidos.json` guardados en `datos_statsbomb`, de cualquier competición y temporada. Las demás tablas corresponden a las consultas anteriores: las de temporada usan `competition_id` y `season_id`, y las de partido usan `match_id`. `df_alineaciones` une ambos equipos en una sola tabla. `bases_df` permite acceder a todas por nombre.

In [26]:
df_competiciones = competiciones
archivos_partidos = sorted(Path("datos_statsbomb").glob("competicion_*/temporada_*/partidos.json"))
df_partidos = pd.DataFrame(
    partido
    for archivo in archivos_partidos
    for partido in json.loads(archivo.read_text(encoding="utf-8"))
)
if not df_partidos.empty:
    df_partidos = df_partidos.drop_duplicates(subset="match_id").reset_index(drop=True)
df_alineaciones = (
    pd.concat(
        [tabla.assign(equipo=equipo) for equipo, tabla in alineaciones.items()],
        ignore_index=True,
    )
    if alineaciones else pd.DataFrame()
)
df_eventos = eventos
df_frames_360 = frames_360
df_jugadores_partido = estadisticas_jugadores_partido
df_equipos_partido = estadisticas_equipos_partido
df_jugadores_temporada = estadisticas_jugadores_temporada
df_equipos_temporada = estadisticas_equipos_temporada

bases_df = {
    "competiciones": df_competiciones,
    "partidos": df_partidos,
    "alineaciones": df_alineaciones,
    "eventos": df_eventos,
    "frames_360": df_frames_360,
    "jugadores_partido": df_jugadores_partido,
    "equipos_partido": df_equipos_partido,
    "jugadores_temporada": df_jugadores_temporada,
    "equipos_temporada": df_equipos_temporada,
}

resumen_bases = pd.DataFrame(
    [{"base": nombre, "filas": len(tabla), "columnas": len(tabla.columns)}
     for nombre, tabla in bases_df.items()]
)
display(resumen_bases)

                  base  filas  columnas
0        competiciones      9        12
1             partidos   1854        62
2         alineaciones     42        15
3              eventos   3538       124
4           frames_360  39429         8
5    jugadores_partido     32       178
6      equipos_partido      2       207
7  jugadores_temporada    615       237
8    equipos_temporada     18       204

In [27]:
df_competiciones.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,73,351,Mexico,Liga MX,male,False,False,2026/2027,2026-10-22T01:00:06.000000,2026-10-22T01:00:06.000000,2026-10-22T01:00:06.000000,2026-10-22T01:00:06.000000
1,73,318,Mexico,Liga MX,male,False,False,2025/2026,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000
2,73,317,Mexico,Liga MX,male,False,False,2024/2025,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000
3,73,281,Mexico,Liga MX,male,False,False,2023/2024,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000
4,73,235,Mexico,Liga MX,male,False,False,2022/2023,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000

In [28]:
df_partidos.head()

,match_id,match_date,kick_off,home_score,away_score,attendance,behind_closed_doors,neutral_ground,collection_status,play_status,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3799476,2021-10-23,22:00:00.000,0.0,1.0,NaN,False,False,Complete,Normal,...,Argentina,2898,Ariel Enrique Holan,None,1960-09-14,11,Argentina,1.1.0,2,2
1,3816744,2022-04-20,02:00:00.000,0.0,1.0,NaN,False,False,Complete,Normal,...,Mexico,3391,Ricardo Ferretti,None,1954-02-22,31,Brazil,1.1.0,2,2
2,3832384,2022-05-23,01:06:00.000,3.0,0.0,NaN,False,False,Complete,Normal,...,Uruguay,1001173,Fernando Ortiz,None,1977-12-25,11,Argentina,1.1.0,2,2
3,3816719,2022-04-09,02:00:00.000,1.0,1.0,NaN,False,False,Complete,Normal,...,Mexico,3294,Juan Máximo Reynoso Guzmán,None,1969-12-28,179,Peru,1.1.0,2,2
4,3815231,2021-11-28,01:00:00.000,1.0,3.0,NaN,False,False,Complete,Normal,...,Argentina,4870,Andrés Luciano Lillini,None,1974-08-13,11,Argentina,1.1.0,2,2

In [29]:
df_eventos.head()

,50_50,attacking_direction,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_duel_win_probability,clearance_head,clearance_left_foot,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,right_to_left,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Toluca,1227,00:00:00.000,Starting XI,NaN
1,NaN,left_to_right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 343, 'lineup': [{'player': {'id'...",Necaxa,1221,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Toluca,1227,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Necaxa,1221,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Toluca,1227,00:00:00.000,Half Start,NaN

In [30]:
df_frames_360.head()

,id,visible_area,match_id,teammate,actor,keeper,location,distance_from_edge_of_visible_area
0,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[41.4, 34.3]",14.88
1,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[49.1, 49.6]",14.31
2,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[50.7, 40.4]",20.12
3,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[60.2, 54.5]",18.46
4,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[60.3, 63.6]",9.36

In [31]:
df_alineaciones.head()

,player_id,player_name,player_nickname,birth_date,player_gender,player_height,player_weight,jersey_number,positions,stats,country,skills,formations,events,equipo
0,26268,Alexis Francisco Peña López,Alexis Peña,1996-01-13,male,187.0,81.0,4,"[{'position_id': 3, 'position': 'Right Center ...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Mexico,"{'HOPS': {'rating': 0.5868, 'raw_rating': 443....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't...",Necaxa
1,26312,Cristian Yonathan Calderón Del Real,Cristian Calderón,1997-05-24,male,177.0,66.0,16,"[{'position_id': 8, 'position': 'Left Wing Bac...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Mexico,"{'HOPS': {'rating': 0.5467, 'raw_rating': 414....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't...",Necaxa
2,27762,Luis Ezequiel Unsain,Ezequiel Unsain,1995-03-09,male,188.0,83.0,22,"[{'position_id': 1, 'position': 'Goalkeeper', ...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Argentina,"{'HOPS': {'rating': 0.5166, 'raw_rating': 393....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't...",Necaxa
3,28480,Tomás Oscar Badaloni,Tomás Badaloni,2000-05-02,male,187.0,82.0,9,"[{'position_id': 5, 'position': 'Left Center B...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Argentina,"{'HOPS': {'rating': 0.5807, 'raw_rating': 438....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't...",Necaxa
4,28815,Agustín Palavecino,None,1996-11-09,male,179.0,73.0,8,"[{'position_id': 11, 'position': 'Left Defensi...","{'own_goals': 0, 'goals': 0, 'assists': 1, 'pe...",Argentina,"{'HOPS': {'rating': 0.3514, 'raw_rating': 275....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't...",Necaxa

In [32]:
df_equipos_temporada.head()

,account_id,team_name,team_id,competition_id,competition_name,season_id,season_name,team_female,team_season_matches,team_season_gd,...,team_season_transition_possession_rate,team_season_time_in_transition_pg,team_season_time_in_control_pg,team_season_transition_xg_pg,team_season_transition_xg_conceded_pg,team_season_transition_obv_pg,team_season_transition_obv_conceded_pg,team_season_avg_team_possession_directness,team_season_avg_team_possession_directness_in_control,team_season_avg_team_possession_directness_in_transition
0,41100,América,1229,73,Liga MX,318,2025/2026,False,38,17,...,0.186597,473378.053474,1.126048e+06,0.246345,0.205340,1.008726,0.731307,0.506469,0.492236,0.633129
1,41100,Atlas,1296,73,Liga MX,318,2025/2026,False,36,-15,...,0.196638,397045.845500,7.148278e+05,0.172453,0.335777,0.648232,0.847870,0.498507,0.472655,0.636179
2,41100,Cruz Azul,1224,73,Liga MX,318,2025/2026,False,44,30,...,0.202646,522148.442523,9.368695e+05,0.319651,0.264333,0.943876,0.971734,0.535875,0.518728,0.649179
3,41100,Guadalajara,1297,73,Liga MX,318,2025/2026,False,40,21,...,0.188370,497701.944075,9.941520e+05,0.415433,0.303820,0.985432,0.979473,0.511265,0.497692,0.609159
4,41100,León,1302,73,Liga MX,318,2025/2026,False,34,-27,...,0.192366,476671.899971,9.696429e+05,0.268190,0.320342,0.981189,1.184412,0.509142,0.487921,0.657076

In [33]:

df_competiciones.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,73,351,Mexico,Liga MX,male,False,False,2026/2027,2026-10-22T01:00:06.000000,2026-10-22T01:00:06.000000,2026-10-22T01:00:06.000000,2026-10-22T01:00:06.000000
1,73,318,Mexico,Liga MX,male,False,False,2025/2026,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000
2,73,317,Mexico,Liga MX,male,False,False,2024/2025,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000
3,73,281,Mexico,Liga MX,male,False,False,2023/2024,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000
4,73,235,Mexico,Liga MX,male,False,False,2022/2023,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000

In [34]:

df_equipos_partido.head()

,account_id,match_id,team_id,team_name,opposition_id,opposition_name,competition_id,competition_name,season_id,season_name,...,team_match_transition_possession_rate,team_match_time_in_transition,team_match_time_in_control,team_match_transition_xg,team_match_transition_xg_conceded,team_match_transition_obv,team_match_transition_obv_conceded,team_match_avg_team_possession_directness,team_match_avg_team_possession_directness_in_control,team_match_avg_team_possession_directness_in_transition
0,41100,4004046,1227,Toluca,1221,Necaxa,73,Liga MX,318,2025/2026,...,0.205000,431460.0,1146413.0,0.000000,0.597497,0.929267,1.850932,0.520801,0.485136,0.813583
1,41100,4004046,1221,Necaxa,1227,Toluca,73,Liga MX,318,2025/2026,...,0.194175,464283.0,877390.0,0.597497,0.000000,1.850932,0.929267,0.513537,0.484363,0.708028

In [35]:

df_equipos_partido.head()

,account_id,match_id,team_id,team_name,opposition_id,opposition_name,competition_id,competition_name,season_id,season_name,...,team_match_transition_possession_rate,team_match_time_in_transition,team_match_time_in_control,team_match_transition_xg,team_match_transition_xg_conceded,team_match_transition_obv,team_match_transition_obv_conceded,team_match_avg_team_possession_directness,team_match_avg_team_possession_directness_in_control,team_match_avg_team_possession_directness_in_transition
0,41100,4004046,1227,Toluca,1221,Necaxa,73,Liga MX,318,2025/2026,...,0.205000,431460.0,1146413.0,0.000000,0.597497,0.929267,1.850932,0.520801,0.485136,0.813583
1,41100,4004046,1221,Necaxa,1227,Toluca,73,Liga MX,318,2025/2026,...,0.194175,464283.0,877390.0,0.597497,0.000000,1.850932,0.929267,0.513537,0.484363,0.708028

In [36]:

df_jugadores_partido.head()

,account_id,match_id,team_id,team_name,player_id,player_name,player_match_minutes,player_match_np_xg,player_match_np_shots,player_match_goals,...,player_match_fhalf_obv_passes_360,player_match_f3_obv_passes_360,player_match_challenge_ratio,player_match_obv_defensive_action,player_match_average_lbp_to_space_distance,player_match_fhalf_average_lbp_to_space_distance,player_match_f3_average_lbp_to_space_distance,player_match_aerial_ratio,player_match_box_cross_ratio,player_match_claim_success
0,41100,4004046,1221,Necaxa,27762,Luis Ezequiel Unsain,97.370100,0.000000,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41100,4004046,1227,Toluca,18784,João Paulo Dias Fernandes,67.012850,0.544052,3,0,...,-0.107849,-0.082712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41100,4004046,1221,Necaxa,26312,Cristian Yonathan Calderón Del Real,84.759583,0.000000,0,0,...,0.012735,0.008121,0.000000,0.056141,5.850117,4.166835,4.166835,NaN,NaN,NaN
3,41100,4004046,1221,Necaxa,31462,José Iván Rodríguez Rebollar,84.759583,0.000000,0,0,...,0.054474,0.018808,0.666667,-0.036769,2.381114,2.468333,NaN,0.5,NaN,NaN
4,41100,4004046,1227,Toluca,87434,Robert Osmar Morales Benítez,30.357250,0.000000,0,0,...,0.003942,-0.001854,1.000000,-0.047213,9.587577,9.587577,NaN,1.0,NaN,NaN

In [37]:

df_jugadores_temporada.head()

,account_id,player_id,player_name,team_id,team_name,competition_id,competition_name,season_id,season_name,country_id,...,player_season_pressured_pass_length_ratio,player_season_obv_shot_90,player_season_average_lbp_to_space_distance,player_season_fhalf_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_received_distance,player_season_penalty_conversion_ratio,player_season_gsaa_ratio,player_season_ot_shots_faced_ratio,player_season_obv_gk_90
0,41100,126602,Anwar Kameel Ben Rhouma Torres,2773,Mazatlán,73,Liga MX,318,2025/2026,241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41100,35477,Cade Dylan Cowell,1297,Guadalajara,73,Liga MX,318,2025/2026,241,...,0.976813,0.080499,3.738889,3.876250,3.876250,4.105087,NaN,NaN,NaN,NaN
2,41100,115623,Daniel Aguirre,1297,Guadalajara,73,Liga MX,318,2025/2026,241,...,0.913612,0.010138,4.608344,4.425457,3.884393,4.114299,NaN,NaN,NaN,NaN
3,41100,16259,Marco Antonio Farfan,1300,Tigres UANL,73,Liga MX,318,2025/2026,241,...,0.938596,-0.025093,4.450345,4.444000,4.138000,6.739167,NaN,NaN,NaN,NaN
4,41100,45608,Walter Portales,1226,Puebla,73,Liga MX,318,2025/2026,241,...,0.876377,-0.013762,5.130000,4.216667,3.700000,6.160000,NaN,NaN,NaN,NaN