# Datos de StatsBomb

Ejecuta las celdas en orden. La cuenta tiene acceso a varias temporadas de Liga MX y Liga MX Femenil. Cada bloque importa un recurso de la API como DataFrame o diccionario de DataFrames.

## 0. Librerías y credenciales

Las credenciales están en `.env`, excluido de Git. Usa el kernel **Python (Hackaton-America)**. [Referencia del cliente oficial](https://github.com/hudl/statsbombpy/blob/master/README.md).

In [1]:
import json
import os
from pathlib import Path

import numpy as np
import pandas as pd
import requests
import sklearn
from dotenv import load_dotenv

load_dotenv(".env")
usuario = os.getenv("API_USERNAME")
contrasena = os.getenv("API_PASSWORD")
if not usuario or not contrasena:
    raise ValueError("Completa API_USERNAME y API_PASSWORD en .env")
credenciales = {"user": usuario, "passwd": contrasena}

from statsbombpy import sb

print(f"pandas {pd.__version__} | numpy {np.__version__} | scikit-learn {sklearn.__version__}")

pandas 2.3.3 | numpy 2.3.5 | scikit-learn 1.9.1

## 1. Competiciones y temporadas

`competiciones` contiene todas las combinaciones disponibles para esta cuenta. Los identificadores `competition_id` y `season_id` sirven para las siguientes consultas.

In [2]:
competiciones = sb.competitions(creds=credenciales)
display(competiciones[["competition_id", "season_id", "competition_name", "season_name"]])

   competition_id  season_id competition_name season_name
0              73        351          Liga MX   2026/2027
1              73        318          Liga MX   2025/2026
2              73        317          Liga MX   2024/2025
3              73        281          Liga MX   2023/2024
4              73        235          Liga MX   2022/2023
5              73        108          Liga MX   2021/2022
6            1438        351  Liga MX Femenil   2026/2027
7            1438        318  Liga MX Femenil   2025/2026
8            1438        317  Liga MX Femenil   2024/2025

## 2. Partidos de una temporada

El ejemplo usa Liga MX 2025/2026. Cambia los identificadores según la tabla anterior.

In [3]:
competition_id = 73
season_id = 318
partidos = sb.matches(competition_id=competition_id, season_id=season_id, creds=credenciales)
display(partidos[["match_id", "match_date", "home_team", "away_team"]].head())

   match_id  match_date    home_team   away_team
0   4004046  2025-07-13       Toluca      Necaxa
1   4059422  2026-05-22    Cruz Azul  Pumas UNAM
2   4038901  2026-03-21       Necaxa     Tijuana
3   4038891  2026-03-15  Tigres UANL   Querétaro
4   4038820  2026-01-17       Necaxa       Atlas

## 3. Elegir un partido

Los siguientes bloques consultan el mismo `match_id`. Puedes cambiarlo por cualquier identificador de `partidos`.

In [4]:
match_id = int(partidos.iloc[0]["match_id"])
print("Partido seleccionado:", match_id)

Partido seleccionado: 4004046

## 4. Alineaciones

El resultado es un diccionario: cada equipo tiene su propio DataFrame.

In [5]:
alineaciones = sb.lineups(match_id=match_id, creds=credenciales)
for equipo, tabla in alineaciones.items():
    print(equipo, len(tabla), "jugadores")
    display(tabla.head())

Necaxa 21 jugadores

,player_id,player_name,player_nickname,birth_date,player_gender,player_height,player_weight,jersey_number,positions,stats,country,skills,formations,events
0,26268,Alexis Francisco Peña López,Alexis Peña,1996-01-13,male,187.0,81.0,4,"[{'position_id': 3, 'position': 'Right Center ...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Mexico,"{'HOPS': {'rating': 0.5868, 'raw_rating': 443....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
1,26312,Cristian Yonathan Calderón Del Real,Cristian Calderón,1997-05-24,male,177.0,66.0,16,"[{'position_id': 8, 'position': 'Left Wing Bac...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Mexico,"{'HOPS': {'rating': 0.5467, 'raw_rating': 414....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
2,27762,Luis Ezequiel Unsain,Ezequiel Unsain,1995-03-09,male,188.0,83.0,22,"[{'position_id': 1, 'position': 'Goalkeeper', ...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Argentina,"{'HOPS': {'rating': 0.5166, 'raw_rating': 393....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
3,28480,Tomás Oscar Badaloni,Tomás Badaloni,2000-05-02,male,187.0,82.0,9,"[{'position_id': 5, 'position': 'Left Center B...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Argentina,"{'HOPS': {'rating': 0.5807, 'raw_rating': 438....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
4,28815,Agustín Palavecino,None,1996-11-09,male,179.0,73.0,8,"[{'position_id': 11, 'position': 'Left Defensi...","{'own_goals': 0, 'goals': 0, 'assists': 1, 'pe...",Argentina,"{'HOPS': {'rating': 0.3514, 'raw_rating': 275....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."

Toluca 21 jugadores

,player_id,player_name,player_nickname,birth_date,player_gender,player_height,player_weight,jersey_number,positions,stats,country,skills,formations,events
0,5575,Héctor Miguel Herrera López,Héctor Herrera,1990-04-19,male,183.0,70.0,16,[],[],Mexico,"{'HOPS': {'rating': 0.4781, 'raw_rating': 367....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
1,5576,Jesús Daniel Gallardo Vasconcelos,Jesús Gallardo,1994-08-15,male,178.0,70.0,20,"[{'position_id': 6, 'position': 'Left Back', '...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Mexico,"{'HOPS': {'rating': 0.5727, 'raw_rating': 433....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
2,18784,João Paulo Dias Fernandes,Paulinho,1992-11-09,male,188.0,75.0,26,"[{'position_id': 23, 'position': 'Center Forwa...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Portugal,"{'HOPS': {'rating': 0.59, 'raw_rating': 445.46...","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
3,25135,Luan Garcia Teixeira,Luan,1993-05-10,male,189.0,86.0,13,"[{'position_id': 3, 'position': 'Right Center ...","{'own_goals': 0, 'goals': 0, 'assists': 0, 'pe...",Brazil,"{'HOPS': {'rating': 0.6386, 'raw_rating': 481....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."
4,25342,Helio Junio Nunes de Castro,Helinho,2000-04-25,male,175.0,66.0,11,"[{'position_id': 24, 'position': 'Left Center ...","{'own_goals': 0, 'goals': 1, 'assists': 0, 'pe...",Brazil,"{'HOPS': {'rating': 0.4127, 'raw_rating': 320....","[{'period': 1, 'timestamp': '00:00:00.000', 'r...","[{'period': 1, 'timestamp': '00:00:00.000', 't..."

## 5. Eventos

Pases, tiros y el resto de acciones del partido en un DataFrame.

In [6]:
eventos = sb.events(match_id=match_id, creds=credenciales)
print(len(eventos), "eventos")
display(eventos.head())

3538 eventos

/mnt/c/Users/Adrián/Desktop/Hackaton-America/.venv/lib/python3.14/site-packages/statsbombpy/sb.py:173: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  events = pd.concat([*events.values()], axis=0, ignore_index=True, sort=True)

,50_50,attacking_direction,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_duel_win_probability,clearance_head,clearance_left_foot,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,right_to_left,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Toluca,1227,00:00:00.000,Starting XI,NaN
1,NaN,left_to_right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 343, 'lineup': [{'player': {'id'...",Necaxa,1221,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Toluca,1227,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Necaxa,1221,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Toluca,1227,00:00:00.000,Half Start,NaN

## 6. Datos 360

Posiciones de jugadores visibles y áreas visibles asociadas a eventos, si están disponibles. Esta tabla puede ser grande.

In [7]:
frames_360 = sb.frames(match_id=match_id, creds=credenciales)
print(len(frames_360), "filas 360")
display(frames_360.head())

39429 filas 360

,id,visible_area,match_id,teammate,actor,keeper,location,distance_from_edge_of_visible_area
0,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[41.4, 34.3]",14.88
1,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[49.1, 49.6]",14.31
2,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[50.7, 40.4]",20.12
3,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[60.2, 54.5]",18.46
4,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[60.3, 63.6]",9.36

## 7. Estadísticas de jugadores por partido

In [8]:
estadisticas_jugadores_partido = sb.player_match_stats(match_id=match_id, creds=credenciales)
print(len(estadisticas_jugadores_partido), "jugadores")
display(estadisticas_jugadores_partido.head())

32 jugadores

,account_id,match_id,team_id,team_name,player_id,player_name,player_match_minutes,player_match_np_xg,player_match_np_shots,player_match_goals,...,player_match_fhalf_obv_passes_360,player_match_f3_obv_passes_360,player_match_challenge_ratio,player_match_obv_defensive_action,player_match_average_lbp_to_space_distance,player_match_fhalf_average_lbp_to_space_distance,player_match_f3_average_lbp_to_space_distance,player_match_aerial_ratio,player_match_box_cross_ratio,player_match_claim_success
0,41100,4004046,1221,Necaxa,27762,Luis Ezequiel Unsain,97.370100,0.000000,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41100,4004046,1227,Toluca,18784,João Paulo Dias Fernandes,67.012850,0.544052,3,0,...,-0.107849,-0.082712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41100,4004046,1221,Necaxa,26312,Cristian Yonathan Calderón Del Real,84.759583,0.000000,0,0,...,0.012735,0.008121,0.000000,0.056141,5.850117,4.166835,4.166835,NaN,NaN,NaN
3,41100,4004046,1221,Necaxa,31462,José Iván Rodríguez Rebollar,84.759583,0.000000,0,0,...,0.054474,0.018808,0.666667,-0.036769,2.381114,2.468333,NaN,0.5,NaN,NaN
4,41100,4004046,1227,Toluca,87434,Robert Osmar Morales Benítez,30.357250,0.000000,0,0,...,0.003942,-0.001854,1.000000,-0.047213,9.587577,9.587577,NaN,1.0,NaN,NaN

## 8. Estadísticas de equipos por partido

In [9]:
estadisticas_equipos_partido = sb.team_match_stats(match_id=match_id, creds=credenciales)
print(len(estadisticas_equipos_partido), "equipos")
display(estadisticas_equipos_partido.head())

2 equipos

,account_id,match_id,team_id,team_name,opposition_id,opposition_name,competition_id,competition_name,season_id,season_name,...,team_match_transition_possession_rate,team_match_time_in_transition,team_match_time_in_control,team_match_transition_xg,team_match_transition_xg_conceded,team_match_transition_obv,team_match_transition_obv_conceded,team_match_avg_team_possession_directness,team_match_avg_team_possession_directness_in_control,team_match_avg_team_possession_directness_in_transition
0,41100,4004046,1227,Toluca,1221,Necaxa,73,Liga MX,318,2025/2026,...,0.205000,431460.0,1146413.0,0.000000,0.597497,0.929267,1.850932,0.520801,0.485136,0.813583
1,41100,4004046,1221,Necaxa,1227,Toluca,73,Liga MX,318,2025/2026,...,0.194175,464283.0,877390.0,0.597497,0.000000,1.850932,0.929267,0.513537,0.484363,0.708028

## 9. Estadísticas de jugadores por temporada

In [10]:
estadisticas_jugadores_temporada = sb.player_season_stats(
    competition_id=competition_id, season_id=season_id, creds=credenciales
)
print(len(estadisticas_jugadores_temporada), "jugadores")
display(estadisticas_jugadores_temporada.head())

615 jugadores

,account_id,player_id,player_name,team_id,team_name,competition_id,competition_name,season_id,season_name,country_id,...,player_season_average_lbp_to_space_distance,player_season_fhalf_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_received_distance,player_first_name,player_last_name,player_season_penalty_conversion_ratio,player_season_gsaa_ratio,player_season_ot_shots_faced_ratio,player_season_obv_gk_90
0,41100,126602,Anwar Kameel Ben Rhouma Torres,2773,Mazatlán,73,Liga MX,318,2025/2026,241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41100,45608,Walter Portales,1226,Puebla,73,Liga MX,318,2025/2026,241,...,5.130000,4.216667,3.700000,6.160000,NaN,NaN,NaN,NaN,NaN,NaN
2,41100,30538,Richard Ledezma,1297,Guadalajara,73,Liga MX,318,2025/2026,241,...,4.559388,4.533135,4.095083,5.726276,Richard,Ledezma,NaN,NaN,NaN,NaN
3,41100,25439,Daniel Ulises Leyva,1221,Necaxa,73,Liga MX,318,2025/2026,241,...,5.158472,4.799677,3.851111,4.081154,Danny,Leyva,NaN,NaN,NaN,NaN
4,41100,35477,Cade Dylan Cowell,1297,Guadalajara,73,Liga MX,318,2025/2026,241,...,3.738889,3.876250,3.876250,4.105087,Cade,Cowell,NaN,NaN,NaN,NaN

## 10. Estadísticas de equipos por temporada

In [11]:
estadisticas_equipos_temporada = sb.team_season_stats(
    competition_id=competition_id, season_id=season_id, creds=credenciales
)
print(len(estadisticas_equipos_temporada), "equipos")
display(estadisticas_equipos_temporada.head())

18 equipos

,account_id,team_name,team_id,competition_id,competition_name,season_id,season_name,team_female,team_season_matches,team_season_gd,...,team_season_transition_possession_rate,team_season_time_in_transition_pg,team_season_time_in_control_pg,team_season_transition_xg_pg,team_season_transition_xg_conceded_pg,team_season_transition_obv_pg,team_season_transition_obv_conceded_pg,team_season_avg_team_possession_directness,team_season_avg_team_possession_directness_in_control,team_season_avg_team_possession_directness_in_transition
0,41100,América,1229,73,Liga MX,318,2025/2026,False,38,17,...,0.186597,473378.053474,1.126048e+06,0.246345,0.205340,1.008726,0.731307,0.506469,0.492236,0.633129
1,41100,Atlas,1296,73,Liga MX,318,2025/2026,False,36,-15,...,0.196638,397045.845500,7.148278e+05,0.172453,0.335777,0.648232,0.847870,0.498507,0.472655,0.636179
2,41100,Cruz Azul,1224,73,Liga MX,318,2025/2026,False,44,30,...,0.202646,522148.442523,9.368695e+05,0.319651,0.264333,0.943876,0.971734,0.535875,0.518728,0.649179
3,41100,Guadalajara,1297,73,Liga MX,318,2025/2026,False,40,21,...,0.188370,497701.944075,9.941520e+05,0.415433,0.303820,0.985432,0.979473,0.511265,0.497692,0.609159
4,41100,León,1302,73,Liga MX,318,2025/2026,False,34,-27,...,0.192366,476671.899971,9.696429e+05,0.268190,0.320342,0.981189,1.184412,0.509142,0.487921,0.657076

## 11. Descargar todos los recursos de las temporadas de Liga MX

La función siguiente recorre cada temporada de Liga MX disponible y guarda un archivo JSON por recurso, partido o temporada en `datos_statsbomb/`. Omite archivos ya descargados, de modo que se puede reanudar. Una descarga completa requiere miles de peticiones y bastante espacio; ejecútala expresamente con `descargar_todo()`. Para comprobarla primero con un partido, usa `descargar_todo(max_partidos=1)`.

In [12]:
def descargar_todo(max_partidos=None, destino="datos_statsbomb"):
    """Guarda todos los recursos accesibles sin acumularlos en memoria."""
    raiz = Path(destino)
    raiz.mkdir(parents=True, exist_ok=True)
    recursos_partido = {
        "alineaciones": sb.lineups,
        "eventos": sb.events,
        "frames_360": sb.frames,
        "jugadores_partido": sb.player_match_stats,
        "equipos_partido": sb.team_match_stats,
    }
    recursos_temporada = {
        "jugadores_temporada": sb.player_season_stats,
        "equipos_temporada": sb.team_season_stats,
    }
    errores = []
    descargados = 0
    partidos_procesados = 0

    def guardar_json(ruta, obtener):
        nonlocal descargados
        if ruta.exists():
            return
        ruta.parent.mkdir(parents=True, exist_ok=True)
        try:
            datos = obtener()
            temporal = ruta.with_suffix(".json.tmp")
            with temporal.open("w", encoding="utf-8") as archivo:
                json.dump(datos, archivo, ensure_ascii=False)
            temporal.replace(ruta)
            descargados += 1
        except Exception as exc:
            errores.append((str(ruta), f"{type(exc).__name__}: {exc}"))

    # Solo Liga MX varonil (competition_id 73).
    competiciones_liga_mx = competiciones.loc[competiciones["competition_id"].eq(73)]
    guardar_json(
        raiz / "competiciones.json",
        lambda: competiciones_liga_mx.to_dict("records"),
    )
    for fila in competiciones_liga_mx.itertuples(index=False):
        if max_partidos is not None and partidos_procesados >= max_partidos:
            break
        cid, sid = int(fila.competition_id), int(fila.season_id)
        carpeta = raiz / f"competicion_{cid}" / f"temporada_{sid}"
        try:
            lista_partidos = sb.matches(competition_id=cid, season_id=sid, creds=credenciales)
        except Exception as exc:
            errores.append((str(carpeta / "partidos.json"), f"{type(exc).__name__}: {exc}"))
            continue
        guardar_json(carpeta / "partidos.json", lambda p=lista_partidos: p.to_dict("records"))
        for nombre, funcion in recursos_temporada.items():
            guardar_json(
                carpeta / f"{nombre}.json",
                lambda f=funcion, c=cid, s=sid: f(competition_id=c, season_id=s, fmt="json", creds=credenciales),
            )
        for mid in lista_partidos["match_id"].astype(int):
            if max_partidos is not None and partidos_procesados >= max_partidos:
                print(f"Archivos nuevos: {descargados}; partidos visitados: {partidos_procesados}; errores: {len(errores)}")
                return errores
            for nombre, funcion in recursos_partido.items():
                guardar_json(
                    carpeta / nombre / f"{mid}.json",
                    lambda f=funcion, m=mid: f(match_id=m, fmt="json", creds=credenciales),
                )
            partidos_procesados += 1
    print(f"Archivos nuevos: {descargados}; partidos visitados: {partidos_procesados}; errores: {len(errores)}")
    return errores

# Ejecuta una de estas líneas cuando quieras guardar los datos:
# errores = descargar_todo(max_partidos=1)  # prueba pequeña
# errores = descargar_todo()                # descarga completa

In [13]:
# 13. Descarga paralela de partidos, eventos, estadísticas de equipo, alineaciones y 360 de Liga MX.
# Ajusta max_trabajadores (predeterminado: 4). Los archivos completos se reutilizan al reanudar.

from concurrent.futures import ThreadPoolExecutor, as_completed
import time


def descargar_bases_todas(destino="datos_statsbomb", max_trabajadores=4):
    if max_trabajadores < 1:
        raise ValueError("max_trabajadores debe ser al menos 1")
    raiz = Path(destino)
    recursos = {
        "eventos": sb.events,
        "equipos_partido": sb.team_match_stats,
        "alineaciones": sb.lineups,
        "frames_360": sb.frames,
    }
    catalogo = sb.competitions(creds=credenciales)
    # Solo Liga MX varonil (competition_id 73).
    catalogo = catalogo.loc[catalogo["competition_id"].eq(73)]
    if catalogo.empty:
        raise RuntimeError("La API no devolvió temporadas de Liga MX; no se inició la descarga.")

    raiz.mkdir(parents=True, exist_ok=True)
    df_partidos_temporadas = []
    inventario = []
    errores = []

    def guardar(ruta, datos):
        ruta.parent.mkdir(parents=True, exist_ok=True)
        temporal = ruta.with_suffix(".json.tmp")
        try:
            with temporal.open("w", encoding="utf-8") as archivo:
                json.dump(datos, archivo, ensure_ascii=False)
            temporal.replace(ruta)
        finally:
            temporal.unlink(missing_ok=True)

    def descargar_uno(nombre, funcion, mid, ruta):
        for intento in range(3):
            try:
                datos = funcion(match_id=mid, fmt="json", creds=credenciales)
                if not datos:
                    return "respuesta_vacia", None
                guardar(ruta, datos)
                return "descargado", None
            except Exception as exc:
                if intento == 2:
                    return "error", f"{type(exc).__name__}: {exc}"
                time.sleep(2 ** intento)

    for comp in catalogo.drop_duplicates(["competition_id", "season_id"]).itertuples(index=False):
        cid, sid = int(comp.competition_id), int(comp.season_id)
        carpeta = raiz / f"competicion_{cid}" / f"temporada_{sid}"
        print(f"Consultando {comp.competition_name} {comp.season_name}...")
        try:
            partidos_temporada = sb.matches(
                competition_id=cid, season_id=sid, creds=credenciales)
            if partidos_temporada.empty:
                raise ValueError("La API devolvió una lista de partidos vacía")
            guardar(carpeta / "partidos.json", partidos_temporada.to_dict("records"))
        except Exception as exc:
            errores.append({"competition_id": cid, "season_id": sid,
                            "recurso": "partidos", "error": str(exc)})
            print(f"  No se pudo consultar la temporada: {type(exc).__name__}")
            continue

        df_partidos_temporadas.append(partidos_temporada)
        tareas = []
        for partido in partidos_temporada.itertuples(index=False):
            mid = int(partido.match_id)
            for nombre, funcion in recursos.items():
                disponible = (partido.match_status_360 == "available"
                              if nombre == "frames_360"
                              else partido.match_status == "available")
                ruta = carpeta / nombre / f"{mid}.json"
                info = {"competition_id": cid, "season_id": sid,
                        "temporada": comp.season_name, "match_id": mid,
                        "local": partido.home_team, "visitante": partido.away_team,
                        "recurso": nombre, "archivo": str(ruta)}
                if not disponible:
                    inventario.append({**info, "estado": "no_disponible_en_catalogo"})
                elif ruta.is_file() and ruta.stat().st_size > 2:
                    inventario.append({**info, "estado": "ya_descargado"})
                else:
                    tareas.append((info, nombre, funcion, mid, ruta))

        ejecutor = ThreadPoolExecutor(max_workers=max_trabajadores)
        try:
            futuros = {
                ejecutor.submit(descargar_uno, nombre, funcion, mid, ruta): info
                for info, nombre, funcion, mid, ruta in tareas
            }
            for indice, futuro in enumerate(as_completed(futuros), start=1):
                info = futuros[futuro]
                estado, error = futuro.result()
                inventario.append({**info, "estado": estado})
                if error:
                    errores.append({**info, "error": error})
                if indice % 100 == 0 or indice == len(tareas):
                    print(f"  {indice}/{len(tareas)} recursos consultados")
        finally:
            ejecutor.shutdown(wait=True, cancel_futures=True)
        print(f"  {len(partidos_temporada)} partidos revisados")

    df_partidos_todos = (pd.concat(df_partidos_temporadas, ignore_index=True)
                         .drop_duplicates("match_id").reset_index(drop=True)
                         if df_partidos_temporadas else pd.DataFrame())
    return df_partidos_todos, pd.DataFrame(inventario), pd.DataFrame(errores)


df_partidos, df_inventario_descarga, df_errores_descarga = descargar_bases_todas()
print(f"Partidos en df_partidos: {len(df_partidos)}; errores: {len(df_errores_descarga)}")
if not df_inventario_descarga.empty:
    display(df_inventario_descarga.groupby(["temporada", "recurso", "estado"])
            .size().rename("partidos").reset_index())
if not df_errores_descarga.empty:
    display(df_errores_descarga)

Consultando Liga MX 2026/2027...
  100/320 recursos consultados
  200/320 recursos consultados
  300/320 recursos consultados
  320/320 recursos consultados
  153 partidos revisados
Consultando Liga MX 2025/2026...
  100/1335 recursos consultados
  200/1335 recursos consultados
  300/1335 recursos consultados
  400/1335 recursos consultados
  500/1335 recursos consultados
  600/1335 recursos consultados
  700/1335 recursos consultados
  800/1335 recursos consultados
  900/1335 recursos consultados
  1000/1335 recursos consultados
  1100/1335 recursos consultados
  1200/1335 recursos consultados
  1300/1335 recursos consultados
  1335/1335 recursos consultados
  337 partidos revisados
Consultando Liga MX 2024/2025...
  100/1356 recursos consultados
  200/1356 recursos consultados
  300/1356 recursos consultados
  400/1356 recursos consultados
  500/1356 recursos consultados
  600/1356 recursos consultados
  700/1356 recursos consultados
  800/1356 recursos consultados
  900/1356 recursos consultados
https://data.statsbombservices.com/api/v2/360-frames/3972031 -> 502
https://data.statsbombservices.com/api/v5/lineups/3939863 -> 502
https://data.statsbombservices.com/api/v11/events/3939960 -> 502
  1000/1356 recursos consultados
  1100/1356 recursos consultados
  1200/1356 recursos consultados
  1300/1356 recursos consultados
  1356/1356 recursos consultados
  340 partidos revisados
Consultando Liga MX 2023/2024...
  100/1356 recursos consultados
  200/1356 recursos consultados
  300/1356 recursos consultados
  400/1356 recursos consultados
https://data.statsbombservices.com/api/v2/360-frames/3918955 -> 502
  500/1356 recursos consultados
  600/1356 recursos consultados
  700/1356 recursos consultados
  800/1356 recursos consultados
  900/1356 recursos consultados
  1000/1356 recursos consultados
  1100/1356 recursos consultados
  1200/1356 recursos consultados
  1300/1356 recursos consultados
  1356/1356 recursos consultados
  340 partidos revisados
Consultando Liga MX 2022/2023...
  100/1364 recursos consultados
  200/1364 recursos consultados
  300/1364 recursos consultados
  400/1364 recursos consultados
  500/1364 recursos consultados
  600/1364 recursos consultados
  700/1364 recursos consultados
  800/1364 recursos consultados
  900/1364 recursos consultados
  1000/1364 recursos consultados
  1100/1364 recursos consultados
  1200/1364 recursos consultados
  1300/1364 recursos consultados
  1364/1364 recursos consultados
  342 partidos revisados
Consultando Liga MX 2021/2022...
  100/1363 recursos consultados
https://data.statsbombservices.com/api/v11/events/3816665 -> 502
https://data.statsbombservices.com/api/v2/360-frames/3799451 -> 502
https://data.statsbombservices.com/api/v5/lineups/3815229 -> 502
  200/1363 recursos consultados
  300/1363 recursos consultados
  400/1363 recursos consultados
  500/1363 recursos consultados
  600/1363 recursos consultados
  700/1363 recursos consultados
  800/1363 recursos consultados
  900/1363 recursos consultados
  1000/1363 recursos consultados
  1100/1363 recursos consultados
  1200/1363 recursos consultados
  1300/1363 recursos consultados
  1363/1363 recursos consultados
  342 partidos revisados
Partidos en df_partidos: 1854; errores: 0

    temporada          recurso                     estado  partidos
0   2021/2022     alineaciones                 descargado       340
1   2021/2022     alineaciones            respuesta_vacia         1
2   2021/2022     alineaciones              ya_descargado         1
3   2021/2022  equipos_partido                 descargado       341
4   2021/2022  equipos_partido              ya_descargado         1
..        ...              ...                        ...       ...
56  2026/2027          eventos  no_disponible_en_catalogo        46
57  2026/2027          eventos              ya_descargado        26
58  2026/2027       frames_360                 descargado        77
59  2026/2027       frames_360  no_disponible_en_catalogo        51
60  2026/2027       frames_360              ya_descargado        25

[61 rows x 4 columns]

In [ ]:
# 12. Prueba de velocidad: un partido nuevo por temporada de Liga MX.
# Guarda la muestra en datos_statsbomb para que la descarga completa pueda reutilizarla.

from concurrent.futures import ThreadPoolExecutor, as_completed
from time import perf_counter


def probar_descarga_muestra(destino="datos_statsbomb", max_trabajadores=4):
    """Descarga un partido nuevo por temporada de Liga MX y mide los cuatro recursos."""
    raiz = Path(destino)
    recursos = {
        "eventos": sb.events,
        "equipos_partido": sb.team_match_stats,
        "alineaciones": sb.lineups,
        "frames_360": sb.frames,
    }
    catalogo = sb.competitions(creds=credenciales)
    catalogo = catalogo.loc[catalogo["competition_id"].eq(73)]
    if catalogo.empty:
        raise RuntimeError("No se encontraron temporadas de Liga MX")

    def guardar(ruta, datos):
        ruta.parent.mkdir(parents=True, exist_ok=True)
        temporal = ruta.with_suffix(".json.tmp")
        try:
            with temporal.open("w", encoding="utf-8") as archivo:
                json.dump(datos, archivo, ensure_ascii=False)
            temporal.replace(ruta)
        finally:
            temporal.unlink(missing_ok=True)

    inicio_total = perf_counter()
    catalogos = []
    tareas = []
    for comp in catalogo.drop_duplicates(["competition_id", "season_id"]).itertuples(index=False):
        cid, sid = int(comp.competition_id), int(comp.season_id)
        partidos_temporada = sb.matches(
            competition_id=cid, season_id=sid, creds=credenciales)
        carpeta = raiz / f"competicion_{cid}" / f"temporada_{sid}"
        guardar(carpeta / "partidos.json", partidos_temporada.to_dict("records"))
        candidatos = partidos_temporada.loc[
            partidos_temporada["match_status"].eq("available")
            & partidos_temporada["match_status_360"].eq("available")
        ]
        # Una ejecución posterior elige otro partido si este ya se descargó.
        elegido = None
        for partido in candidatos.itertuples(index=False):
            mid = int(partido.match_id)
            if all(not (carpeta / nombre / f"{mid}.json").exists()
                   for nombre in recursos):
                elegido = mid
                break
        catalogos.append({
            "temporada": comp.season_name,
            "partidos": len(partidos_temporada),
            "eventos_disponibles": int(partidos_temporada["match_status"].eq("available").sum()),
            "360_disponibles": int(partidos_temporada["match_status_360"].eq("available").sum()),
            "match_id_muestra": elegido,
        })
        if elegido is not None:
            for nombre, funcion in recursos.items():
                tareas.append((comp.season_name, elegido, nombre, funcion,
                               carpeta / nombre / f"{elegido}.json"))

    def descargar(tarea):
        temporada, mid, nombre, funcion, ruta = tarea
        inicio = perf_counter()
        try:
            datos = funcion(match_id=mid, fmt="json", creds=credenciales)
            segundos_api = perf_counter() - inicio
            if not datos:
                return {"temporada": temporada, "match_id": mid, "recurso": nombre,
                        "estado": "respuesta_vacia", "bytes": 0,
                        "segundos_api": segundos_api}
            guardar(ruta, datos)
            return {"temporada": temporada, "match_id": mid, "recurso": nombre,
                    "estado": "descargado", "bytes": ruta.stat().st_size,
                    "segundos_api": segundos_api}
        except Exception as exc:
            return {"temporada": temporada, "match_id": mid, "recurso": nombre,
                    "estado": f"error: {type(exc).__name__}", "bytes": 0,
                    "segundos_api": perf_counter() - inicio}

    inicio_archivos = perf_counter()
    with ThreadPoolExecutor(max_workers=max_trabajadores) as ejecutor:
        futuros = [ejecutor.submit(descargar, tarea) for tarea in tareas]
        archivos = [futuro.result() for futuro in as_completed(futuros)]
    segundos_archivos = perf_counter() - inicio_archivos
    segundos_total = perf_counter() - inicio_total
    return (pd.DataFrame(catalogos), pd.DataFrame(archivos),
            segundos_archivos, segundos_total)


df_catalogos_prueba, df_archivos_prueba, segundos_archivos, segundos_total = probar_descarga_muestra()
display(df_catalogos_prueba)
if df_archivos_prueba.empty:
    print("No quedan partidos sin descargar para esta prueba.")
else:
    display(df_archivos_prueba.groupby(["recurso", "estado"]).agg(
        archivos=("match_id", "size"),
        megabytes=("bytes", lambda x: x.sum() / 1_000_000),
        segundos_api_promedio=("segundos_api", "mean"),
    ).reset_index())
    exitos = df_archivos_prueba.loc[df_archivos_prueba["estado"].eq("descargado")]
    promedios = exitos.groupby("recurso")["bytes"].mean()
    n_eventos = int(df_catalogos_prueba["eventos_disponibles"].sum())
    n_360 = int(df_catalogos_prueba["360_disponibles"].sum())
    conteos = {"eventos": n_eventos, "equipos_partido": n_eventos,
               "alineaciones": n_eventos, "frames_360": n_360}
    if all(recurso in promedios for recurso in conteos):
        bytes_estimados = sum(promedios[recurso] * cantidad
                              for recurso, cantidad in conteos.items())
        horas_transferencia_20_mbps = bytes_estimados / 2_500_000 / 3600
        print(f"Tamaño estimado: {bytes_estimados / 1e9:.1f} GB; "
              f"transferencia mínima a 20 Mbps: {horas_transferencia_20_mbps:.1f} h")
    print(f"Tiempo de los archivos: {segundos_archivos:.1f} s; "
          f"total con catálogos: {segundos_total:.1f} s")

## 14. DataFrames para análisis

Este bloque reúne las tablas para análisis. `df_partidos` carga todos los archivos `partidos.json` guardados en `datos_statsbomb`, de cualquier competición y temporada. Las demás tablas corresponden a las consultas anteriores: las de temporada usan `competition_id` y `season_id`, y las de partido usan `match_id`. `df_alineaciones` une ambos equipos en una sola tabla. `bases_df` permite acceder a todas por nombre.

In [13]:
df_competiciones = competiciones
archivos_partidos = sorted(Path("datos_statsbomb").glob("competicion_*/temporada_*/partidos.json"))
df_partidos = pd.DataFrame(
    partido
    for archivo in archivos_partidos
    for partido in json.loads(archivo.read_text(encoding="utf-8"))
)
if not df_partidos.empty:
    df_partidos = df_partidos.drop_duplicates(subset="match_id").reset_index(drop=True)
df_alineaciones = (
    pd.concat(
        [tabla.assign(equipo=equipo) for equipo, tabla in alineaciones.items()],
        ignore_index=True,
    )
    if alineaciones else pd.DataFrame()
)
df_eventos = eventos
df_frames_360 = frames_360
df_jugadores_partido = estadisticas_jugadores_partido
df_equipos_partido = estadisticas_equipos_partido
df_jugadores_temporada = estadisticas_jugadores_temporada
df_equipos_temporada = estadisticas_equipos_temporada

bases_df = {
    "competiciones": df_competiciones,
    "partidos": df_partidos,
    "alineaciones": df_alineaciones,
    "eventos": df_eventos,
    "frames_360": df_frames_360,
    "jugadores_partido": df_jugadores_partido,
    "equipos_partido": df_equipos_partido,
    "jugadores_temporada": df_jugadores_temporada,
    "equipos_temporada": df_equipos_temporada,
}

resumen_bases = pd.DataFrame(
    [{"base": nombre, "filas": len(tabla), "columnas": len(tabla.columns)}
     for nombre, tabla in bases_df.items()]
)
display(resumen_bases)

                  base  filas  columnas
0        competiciones      9        12
1             partidos    490        62
2         alineaciones     42        15
3              eventos   3538       124
4           frames_360  39429         8
5    jugadores_partido     32       178
6      equipos_partido      2       207
7  jugadores_temporada    615       237
8    equipos_temporada     18       204

In [14]:
df_competiciones.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,73,351,Mexico,Liga MX,male,False,False,2026/2027,2026-10-21T09:41:26.000000,2026-10-20T15:15:54.000000,2026-10-20T15:15:54.000000,2026-10-21T09:41:26.000000
1,73,318,Mexico,Liga MX,male,False,False,2025/2026,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000
2,73,317,Mexico,Liga MX,male,False,False,2024/2025,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000
3,73,281,Mexico,Liga MX,male,False,False,2023/2024,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000
4,73,235,Mexico,Liga MX,male,False,False,2022/2023,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000

In [15]:
df_partidos.head()

,match_id,match_date,kick_off,home_score,away_score,attendance,behind_closed_doors,neutral_ground,collection_status,play_status,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,4004046,2025-07-13,01:00:00.000,3.0,1.0,20273.0,False,False,Complete,Normal,...,Argentina,5662.0,Fernando Rubén Gago,None,1986-04-10,11.0,Argentina,1.1.0,2,2
1,4059422,2026-05-22,02:00:00.000,0.0,0.0,42223.0,False,False,Complete,Normal,...,Mexico,1005267.0,Efraín Juárez Váldez,Efraín Váldez,1988-02-22,147.0,Mexico,1.1.0,2,2
2,4038901,2026-03-21,01:00:00.000,3.0,0.0,14840.0,False,False,Complete,Normal,...,Uruguay,4615.0,Washington Sebastián Abreu Gallo,None,1976-10-17,242.0,Uruguay,1.1.0,2,2
3,4038891,2026-03-15,23:00:00.000,0.0,0.0,40217.0,False,False,Complete,Normal,...,Argentina,1004862.0,Esteban Eduardo González Herrera,Esteban González,1982-05-22,45.0,Chile,1.1.0,2,2
4,4038820,2026-01-17,23:00:00.000,0.0,1.0,17557.0,False,False,Complete,Normal,...,Uruguay,2819.0,Diego Martín Cocca Pera,None,1972-02-11,11.0,Argentina,1.1.0,2,2

In [14]:
df_eventos.head()

NameError: name 'df_eventos' is not defined

In [17]:
df_frames_360.head()

,id,visible_area,match_id,teammate,actor,keeper,location,distance_from_edge_of_visible_area
0,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[41.4, 34.3]",14.88
1,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[49.1, 49.6]",14.31
2,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[50.7, 40.4]",20.12
3,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[60.2, 54.5]",18.46
4,f027b9e9-9e90-5275-966a-107ed8ce156d,"[45.58, 73.01, 5.71, 0.0, 115.69, 0.0, 75.39, ...",4004046,True,False,False,"[60.3, 63.6]",9.36

In [ ]:
df_alineaciones.head()

,account_id,player_id,player_name,team_id,team_name,competition_id,competition_name,season_id,season_name,country_id,...,player_season_average_lbp_to_space_distance,player_season_fhalf_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_received_distance,player_first_name,player_last_name,player_season_penalty_conversion_ratio,player_season_gsaa_ratio,player_season_ot_shots_faced_ratio,player_season_obv_gk_90
0,41100,126602,Anwar Kameel Ben Rhouma Torres,2773,Mazatlán,73,Liga MX,318,2025/2026,241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41100,45608,Walter Portales,1226,Puebla,73,Liga MX,318,2025/2026,241,...,5.130000,4.216667,3.700000,6.160000,NaN,NaN,NaN,NaN,NaN,NaN
2,41100,28529,Fernando David Arce Juárez,1227,Toluca,73,Liga MX,318,2025/2026,241,...,6.048261,4.645000,6.280000,2.840000,Fernando,Arce,NaN,NaN,NaN,NaN
3,41100,30538,Richard Ledezma,1297,Guadalajara,73,Liga MX,318,2025/2026,241,...,4.559388,4.533135,4.095083,5.726276,Richard,Ledezma,NaN,NaN,NaN,NaN
4,41100,25439,Daniel Ulises Leyva,1221,Necaxa,73,Liga MX,318,2025/2026,241,...,5.158472,4.799677,3.851111,4.081154,Danny,Leyva,NaN,NaN,NaN,NaN

In [19]:
df_equipos_temporada.head()

,account_id,team_name,team_id,competition_id,competition_name,season_id,season_name,team_female,team_season_matches,team_season_gd,...,team_season_transition_possession_rate,team_season_time_in_transition_pg,team_season_time_in_control_pg,team_season_transition_xg_pg,team_season_transition_xg_conceded_pg,team_season_transition_obv_pg,team_season_transition_obv_conceded_pg,team_season_avg_team_possession_directness,team_season_avg_team_possession_directness_in_control,team_season_avg_team_possession_directness_in_transition
0,41100,América,1229,73,Liga MX,318,2025/2026,False,38,17,...,0.186597,473378.053474,1.126048e+06,0.246345,0.205340,1.008726,0.731307,0.506469,0.492236,0.633129
1,41100,Atlas,1296,73,Liga MX,318,2025/2026,False,36,-15,...,0.196638,397045.845500,7.148278e+05,0.172453,0.335777,0.648232,0.847870,0.498507,0.472655,0.636179
2,41100,Cruz Azul,1224,73,Liga MX,318,2025/2026,False,44,30,...,0.202646,522148.442523,9.368695e+05,0.319651,0.264333,0.943876,0.971734,0.535875,0.518728,0.649179
3,41100,Guadalajara,1297,73,Liga MX,318,2025/2026,False,40,21,...,0.188370,497701.944075,9.941520e+05,0.415433,0.303820,0.985432,0.979473,0.511265,0.497692,0.609159
4,41100,León,1302,73,Liga MX,318,2025/2026,False,34,-27,...,0.192366,476671.899971,9.696429e+05,0.268190,0.320342,0.981189,1.184412,0.509142,0.487921,0.657076

In [20]:

df_competiciones.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,73,351,Mexico,Liga MX,male,False,False,2026/2027,2026-10-21T09:41:26.000000,2026-10-20T15:15:54.000000,2026-10-20T15:15:54.000000,2026-10-21T09:41:26.000000
1,73,318,Mexico,Liga MX,male,False,False,2025/2026,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000,2026-09-30T13:56:47.000000
2,73,317,Mexico,Liga MX,male,False,False,2024/2025,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000,2026-10-21T08:02:22.000000
3,73,281,Mexico,Liga MX,male,False,False,2023/2024,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000,2026-10-21T09:39:40.000000
4,73,235,Mexico,Liga MX,male,False,False,2022/2023,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000,2026-10-21T08:45:25.000000

In [21]:

df_equipos_partido.head()

,account_id,match_id,team_id,team_name,opposition_id,opposition_name,competition_id,competition_name,season_id,season_name,...,team_match_transition_possession_rate,team_match_time_in_transition,team_match_time_in_control,team_match_transition_xg,team_match_transition_xg_conceded,team_match_transition_obv,team_match_transition_obv_conceded,team_match_avg_team_possession_directness,team_match_avg_team_possession_directness_in_control,team_match_avg_team_possession_directness_in_transition
0,41100,4004046,1227,Toluca,1221,Necaxa,73,Liga MX,318,2025/2026,...,0.205000,431460.0,1146413.0,0.000000,0.597497,0.929267,1.850932,0.520801,0.485136,0.813583
1,41100,4004046,1221,Necaxa,1227,Toluca,73,Liga MX,318,2025/2026,...,0.194175,464283.0,877390.0,0.597497,0.000000,1.850932,0.929267,0.513537,0.484363,0.708028

In [22]:

df_equipos_partido.head()

,account_id,match_id,team_id,team_name,opposition_id,opposition_name,competition_id,competition_name,season_id,season_name,...,team_match_transition_possession_rate,team_match_time_in_transition,team_match_time_in_control,team_match_transition_xg,team_match_transition_xg_conceded,team_match_transition_obv,team_match_transition_obv_conceded,team_match_avg_team_possession_directness,team_match_avg_team_possession_directness_in_control,team_match_avg_team_possession_directness_in_transition
0,41100,4004046,1227,Toluca,1221,Necaxa,73,Liga MX,318,2025/2026,...,0.205000,431460.0,1146413.0,0.000000,0.597497,0.929267,1.850932,0.520801,0.485136,0.813583
1,41100,4004046,1221,Necaxa,1227,Toluca,73,Liga MX,318,2025/2026,...,0.194175,464283.0,877390.0,0.597497,0.000000,1.850932,0.929267,0.513537,0.484363,0.708028

In [23]:

df_jugadores_partido.head()

,account_id,match_id,team_id,team_name,player_id,player_name,player_match_minutes,player_match_np_xg,player_match_np_shots,player_match_goals,...,player_match_fhalf_obv_passes_360,player_match_f3_obv_passes_360,player_match_challenge_ratio,player_match_obv_defensive_action,player_match_average_lbp_to_space_distance,player_match_fhalf_average_lbp_to_space_distance,player_match_f3_average_lbp_to_space_distance,player_match_aerial_ratio,player_match_box_cross_ratio,player_match_claim_success
0,41100,4004046,1221,Necaxa,27762,Luis Ezequiel Unsain,97.370100,0.000000,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41100,4004046,1227,Toluca,18784,João Paulo Dias Fernandes,67.012850,0.544052,3,0,...,-0.107849,-0.082712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41100,4004046,1221,Necaxa,26312,Cristian Yonathan Calderón Del Real,84.759583,0.000000,0,0,...,0.012735,0.008121,0.000000,0.056141,5.850117,4.166835,4.166835,NaN,NaN,NaN
3,41100,4004046,1221,Necaxa,31462,José Iván Rodríguez Rebollar,84.759583,0.000000,0,0,...,0.054474,0.018808,0.666667,-0.036769,2.381114,2.468333,NaN,0.5,NaN,NaN
4,41100,4004046,1227,Toluca,87434,Robert Osmar Morales Benítez,30.357250,0.000000,0,0,...,0.003942,-0.001854,1.000000,-0.047213,9.587577,9.587577,NaN,1.0,NaN,NaN

In [24]:

df_jugadores_temporada.head()

,account_id,player_id,player_name,team_id,team_name,competition_id,competition_name,season_id,season_name,country_id,...,player_season_average_lbp_to_space_distance,player_season_fhalf_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_distance,player_season_f3_average_lbp_to_space_received_distance,player_first_name,player_last_name,player_season_penalty_conversion_ratio,player_season_gsaa_ratio,player_season_ot_shots_faced_ratio,player_season_obv_gk_90
0,41100,126602,Anwar Kameel Ben Rhouma Torres,2773,Mazatlán,73,Liga MX,318,2025/2026,241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41100,45608,Walter Portales,1226,Puebla,73,Liga MX,318,2025/2026,241,...,5.130000,4.216667,3.700000,6.160000,NaN,NaN,NaN,NaN,NaN,NaN
2,41100,28529,Fernando David Arce Juárez,1227,Toluca,73,Liga MX,318,2025/2026,241,...,6.048261,4.645000,6.280000,2.840000,Fernando,Arce,NaN,NaN,NaN,NaN
3,41100,30538,Richard Ledezma,1297,Guadalajara,73,Liga MX,318,2025/2026,241,...,4.559388,4.533135,4.095083,5.726276,Richard,Ledezma,NaN,NaN,NaN,NaN
4,41100,25439,Daniel Ulises Leyva,1221,Necaxa,73,Liga MX,318,2025/2026,241,...,5.158472,4.799677,3.851111,4.081154,Danny,Leyva,NaN,NaN,NaN,NaN